### ISSUE TITLE
ASF Download currently not working?

### ISSUE THREAD

**Issue by Scartography** [ESA-PhiLab/OpenSarToolkit#12]
* Requests to get ASF data currently suspended? (at least I can't get the download to work)

**Comment by EthanNguyen132** [comment]
ASF requires login via Oauth2 authorization code. I guess there's a need to enhance the login logic for helpers/asf.py.

**Comment by Scartography** [comment]
Thanks for the hint, yes it needs and update.

TODO: [https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python](https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python)

**Comment by Scartography** [comment]
The solution from earthdata wiki for python works, master implementation TBD.
