### ISSUE TITLE
burst identification not working without dias access

### ISSUE THREAD

**Issue by espiritocz** [ESA-PhiLab/OpenSarToolkit#2]
got SLC data by s1_batch.download. trying to:
s1_batch.burst_inventory_(key=key, refine=True)

but get error:
 Getting burst info from S1A_IW_SLC__1SDV_20180601T165947_20180601T170014_022166_0265B3_4292.zip.
 Getting burst info from S1B_IW_SLC__1SDV_20180607T165904_20180607T165931_011270_014AF7_EE78.zip.
 Dummy function for mundi paths to be added
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-62-eaf8576867c3> in <module>
----> 1 s1_batch.burst_inventory_(key=key, refine=True)
      2 #s1_batch.plot_inventory(s1_batch.burst_inventory, transperancy=0.1)

~/miniconda3/lib/python3.7/site-packages/ost/Project.py in burst_inventory_(self, key, refine)
    343                 self.refined_inventory_dict[key],
    344                 download_dir=self.download_dir,
--> 345                 data_mount=self.data_mount)
    346         else:
    347             self.burst_inventory = burst.burst_inventory(

~/miniconda3/lib/python3.7/site-packages/ost/s1/burst.py in burst_inventory(inventory_df, download_dir, data_mount, uname, pword)
     49             inventory_df.identifier == scene_id].orbitdirection.values[0]
     50 
---> 51         filepath = scene.get_path(download_dir, data_mount)
     52         # print(filepath)
     53         if filepath[-4:] == '.zip':

~/miniconda3/lib/python3.7/site-packages/ost/s1/s1scene.py in get_path(self, download_dir, data_mount)
    169         elif os.path.isdir(self._onda_path(data_mount)):
    170             path = self._onda_path(data_mount)
--> 171         elif os.path.isfile(self._mundi_path(data_mount)):
    172             path = self._mundi_path(data_mount)
    173         elif os.path.isfile(self._aws_path(data_mount)):

~/miniconda3/lib/python3.7/genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except OSError:
     32         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by BuddyVolly** [comment]
Dear espiritocz, 

1.) please update to the new version, running the pip command for installation again. 
2.) burst_inventory_() became create_burst_inventory() function
3.) the path issue with the mundi error message is solved (a bit confusing, but it basically means it did not find it in a downloaded file). For Burst inventory you need to consider 2 things, either data is already downloaded, you have DIAS access (which is not the case), or the data is ONLINE on scihub (which for historical data might not be the case, because of rollling archive policy)

Let me know if this helps!
BV

**Comment by espiritocz** [comment]
hi BV,

I use the current version now. I have downloaded data and used "your tip an trick" to put it under the projDir/download/...
now, I have run scripts as stated in your notebook, including the
s1_batch.create_burst_inventory(refine=True)

but when i run s1batch.burst_to_ard(timeseries=False, timescan=False, mosaic=True, overwrite=False), I again get some error that seems related to the data_mount ??
(will check it further and update you, in case this is not any error familiar to you..)


TypeError                                 Traceback (most recent call last)
<ipython-input-21-092bd53adb86> in <module>
----> 1 s1batch.burst_to_ard(timeseries=False, timescan=False, mosaic=True, overwrite=False)

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/Project.py in burst_to_ard(self, timeseries, timescan, mosaic, overwrite)
    497                                      self.temp_dir,
    498                                      self.ard_parameters,
--> 499                                      self.data_mount)
    500 
    501             nr_of_processed = len(

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/s1/burst.py in burst_to_ard_batch(burst_inventory, download_dir, processing_dir, temp_dir, ard_parameters, data_mount)
    260                      ls_mask_create=ls_mask_create,
    261                      dem=dem,
--> 262                      remove_slave_import=False)
    263 
    264     # return return_code

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/s1/burst_to_ard.py in burst_to_ard(master_file, swath, master_burst_nr, master_burst_id, out_dir, temp_dir, slave_file, slave_burst_nr, slave_burst_id, coherence, polarimetry, pol_speckle_filter, resolution, product_type, speckle_filter, to_db, ls_mask_create, dem, remove_slave_import)
    613         import_log = opj(out_dir, '{}_import.err_log'.format(master_burst_id))
    614         return_code = _import(master_file, master_import, import_log,
--> 615                               swath, master_burst_nr)
    616         if return_code != 0:
    617             h.remove_folder_content(temp_dir)

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/s1/burst_to_ard.py in _import(infile, out_prefix, logfile, swath, burst, polar)
     39 
     40     print(' INFO: Importing Burst {} from Swath {}'
---> 41           ' from scene {}'.format(burst, swath, os.path.basename(infile)))
     42 
     43     command = '{} {} -x -q {} -Pinput={} -Ppolar={} -Pswath={}\

/opt/miniconda/envs/shared/lib/python3.7/posixpath.py in basename(p)
    144 def basename(p):
    145     """Returns the final component of a pathname"""
--> 146     p = os.fspath(p)
    147     sep = _get_sep(p)
    148     i = p.rfind(sep) + 1

TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by espiritocz** [comment]
hi,
so this error was connected to the download issue - there were two mistakes in restore_download_dir function. please see corrected version below. I believe that after the fix you have mentioned earlier, it would all work as a charm )

ost/s1/download.py:
def restore_download_dir(input_directory, download_dir):
    '''Function to create the OST download directory structure

    In case data is already downloaded to a single folder, this function can
    be used to create a OST compliant structure of the download directory.

    Args:
        input_directory: the directory, where the dwonloaded files are located
        download_dir: the high-level directory compliant with OST

    '''
    for scene in glob.glob('{}/*zip'.format(input_directory)):
        # get scene
        s1scene = S1Scene(os.path.basename(scene)[:-4])
        # create download path and file
        filepath = s1scene._download_path(download_dir, True)
        # move file
        os.rename(scene, filepath)
        f=open(filepath+".downloaded","w+")
        f.close()




actually I did also some minor correction to Project.py - I guess this would be helpful, for automatization (added uname and pword):
    def create_burst_inventory(self, key=None, refine=True, uname=None, pword=None):

        if key:
            outfile = opj(self.inventory_dir,
                          'bursts.{}.shp').format(key)
        else:
            outfile = opj(self.inventory_dir,
                          'bursts.full.shp')
        self.burst_inventory = burst.burst_inventory(
                    self.inventory,
                    outfile,
                    download_dir=self.download_dir,
                    data_mount=self.data_mount,
                    uname=uname, pword=pword)

        if refine:
            #print('{}.refined.shp'.format(outfile[:-4]))
            self.burst_inventory = burst.refine_burst_inventory(
                    self.aoi, self.burst_inventory,
                    '{}.refined.shp'.format(outfile[:-4])
                    )

**Comment by BuddyVolly** [comment]
Thanks espiritocz, 

I added your suggestions. You can update now :)
November will be more a testing month, and I hope to solve remaining issues then.
