### ISSUE TITLE
scihub zip check

### ISSUE THREAD

**Issue by espiritocz** [ESA-PhiLab/OpenSarToolkit#3]
hi,
I got an error not allowing me to download data from scihub.
I used the following command:
OurProject.download(OurProject.refined_inventory_dict['ASCENDING_VVVH'], mirror=1, concurrent=1)
(where OurProject is an instance of ost.Sentinel1_GRDBatch)

The data are downloaded normally but some zip check considers it inconsistent. I think this zip check must be too strict J
(i just tried to download a file manually and it was downloaded correctly. so the server should be ok)

 INFO: Checking the zip archive of /.../SAR/GRD/2019/07/24/S1B_IW_GRDH_1SDV_20190724T180118_20190724T180143_017279_0207FA_B270.zip for inconsistency
 INFO: /.../download/SAR/GRD/2019/07/24/S1B_IW_GRDH_1SDV_20190724T180118_20190724T180143_017279_0207FA_B270.zip did not pass the zip test.                   Re-downloading the full scene.

**Comment by espiritocz** [comment]
(solving temporarily by using
https://pypi.org/project/sentinelsat
..)

**Comment by BuddyVolly** [comment]
I will check this, but you can use another mirror, e.g. ASF
