### ISSUE TITLE
UnboundLocalError: local variable 'calibrate_to' referenced before assignment

### ISSUE THREAD

**Issue by behzad89** [ESA-PhiLab/OpenSarToolkit#31]
Hi!

When I try to run the batch routine, I face this error: 

**Script:**
s1_grd.grds_to_ard(
    inventory_df=s1_grd.refined_inventory_dict[key], 
    timeseries=True, 
    timescan=True, 
    mosaic=True, 
    overwrite=False
)

**Error:**
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-28-b8f678370621> in <module>
      4     timescan=True,
      5     mosaic=True,
----> 6     overwrite=False
      7 )

/usr/local/lib/python3.6/dist-packages/ost/Project.py in grds_to_ard(self, inventory_df, subset, timeseries, timescan, mosaic, overwrite, exec_file, cut_to_aoi)
   1121                 subset,
   1122                 self.data_mount,
-> 1123                 exec_file)
   1124 
   1125             # reset number of already processed acquisitions

/usr/local/lib/python3.6/dist-packages/ost/s1/grd_batch.py in grd_to_ard_batch(inventory_df, download_dir, processing_dir, temp_dir, proc_file, subset, data_mount, exec_file)
    139                                           temp_dir,
    140                                           proc_file,
--> 141                                           subset=subset)
    142 
    143 

/usr/local/lib/python3.6/dist-packages/ost/s1/grd_to_ard.py in grd_to_ard(filelist, output_dir, file_id, temp_dir, proc_file, subset)
    909     calibrated = opj(temp_dir, '{}_cal'.format(file_id))
    910     logfile = opj(output_dir, '{}.Calibration.errLog'.format(file_id))
--> 911     return_code = common._calibration(infile, calibrated, logfile, calibrate_to)
    912 
    913     # delete input

UnboundLocalError: local variable 'calibrate_to' referenced before assignment

**Comment by BuddyVolly** [comment]
Hi Behzad, 

we are right now working hard to clean up the code and coming to a stable version. We already did some progress on this, and for us it will be now a waste of time debug older versions (i.e. master branch). You can expect a new beta version within then the next 2-3 weeks thatshould ideally solve it. I will leave a note here.

**Comment by behzad89** [comment]
Hi Buddy,

I will wait for your note :+1:
