### ISSUE TITLE
Similar Issue: ASF Download currently not working?

### ISSUE THREAD

**Issue by AnglinaBhambra** [ESA-PhiLab/OpenSarToolkit#33]
"ValueError:  ERROR: Username/Password are incorrect"

I can't figure out why as this issue was raised previously ([here](https://github.com/ESA-PhiLab/OpenSarToolkit/issues/12)).

**Comment by vincentvaroquaux** [comment]
I had the same issue. The url is redirected first to a mirror, then to the authentication url. The username&password are dropped during the first redirection.

Rewriting `rebuild_auth` in `ost/helpers/asf.py` solves the problem:

```
def rebuild_auth(self, prepared_request, response):

        headers = prepared_request.headers
        url = prepared_request.url
        redirect_parsed = requests.utils.urlparse(url)

        if 'Authorization' in headers:

            original_parsed = requests.utils.urlparse(response.request.url)

            if (original_parsed.hostname != redirect_parsed.hostname) and \
                redirect_parsed.hostname != self.AUTH_HOST:

                del headers['Authorization']

        if redirect_parsed.hostname == self.AUTH_HOST:

            prepared_request.prepare_auth(self.auth)

        return
```

But, I'm not sure if it's secure enough...
