### ISSUE TITLE
Download from ONDA Dias

### ISSUE THREAD

**Issue by vincentvaroquaux** [ESA-PhiLab/OpenSarToolkit#36]
`check_connection` using  `https://catalogue.onda-dias.eu/dias-catalogue/ee89ad93-c6ab-4eb3-b698-4585b4af3ca0)/$value` returns a 403 status (I assume that the product is too old and is not reachable anymore).

A workaround :
```
    if response.status_code == 403:
        return 200
```

**Comment by kr1zz** [comment]
Lovely workaround :D
