### ISSUE TITLE
missing coma in polarization choice

### ISSUE THREAD

**Issue by vincentvaroquaux** [ESA-PhiLab/OpenSarToolkit#37]
I had issues using "VV,VH" polarization.
The two modifications solves the problem :

`ost/Project.py`
`possible_pols = ['*', 'VV', 'VH', 'HV', 'HH', 'VV, VH', 'HH, HV']`

`ost/helpers/settings.py`
`['VV, VH, HH, HV', 'VV', 'VH', 'VV, VH', 'HH, HV', 'VV, HH']`

**Comment by BuddyVolly** [comment]
The space separated pol channels are the way Snap expect them. Can you describe your problem in more detail?

**Comment by vincentvaroquaux** [comment]
Sorry, I mixed two things...
```
ost/Project.py
possible_pols = ['*', 'VV', 'VH', 'HV', 'HH', 'VV VH', 'HH HV']
```
=> This is good, it's for scihub search query

```
ost/helpers/settings.py
['VV, VH, HH, HV', 'VV', 'VH', 'VV, VH', 'HH, HV', 'VV, HH']
```
=> it is used in `burst_import`: `ard['polarisation'].replace(' ', '')`
'VV VH' (without the coma) becomes 'VVVH' and SNAP does not recognize this argument.

Please, compare 'polarisation' and 'coherence_bands' in settings.py :
```
    'polarisation': {'type': str, 'choices':
        ['VV, VH, HH, HV', 'VV', 'VH', 'VV VH', 'HH HV', 'VV, HH']
                     },

    'coherence_bands': {'type': str, 'choices':
        ['VV, VH, HH, HV', 'VV', 'VH', 'VV, VH', 'HH, HV', 'VV, HH']
                        },
```

**Comment by BuddyVolly** [comment]
This is right! Thanks for your support
