### ISSUE TITLE
problems in grd_to_ard

### ISSUE THREAD

**Issue by espiritocz** [ESA-PhiLab/OpenSarToolkit#4]
hi,
I report two issues here:
1)
OurProject.grd_to_ard(subset=None, timeseries=True, timescan=True, mosaic=True)
gives error:
in grd_to_ard(self, inventory_df, subset, timeseries, timescan, mosaic, overwrite)
    682             self.ard_parameters['dem'] = 'ASTER 1sec GDEM'
    683 
--> 684         if subset.split('.')[-1] == '.shp':
    685             subset = str(vec.shp_to_wkt(subset, buffer=0.1, envelope=True))
    686         elif subset.startswith('POLYGON (('):

AttributeError: 'NoneType' object has no attribute 'split'

2) so when I put "aoi" variable to the "subset", where aoi is wkt in the form of "POLYGON ((....", then another error appears:
in grd_to_ard(self, inventory_df, subset, timeseries, timescan, mosaic, overwrite)
    708                                   self.ard_parameters,
    709                                   subset,
--> 710                                   self.data_mount
    711                                   )
    712 

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/s1/grd_batch.py in grd_to_ard_batch(inventory_df, download_dir, processing_dir, temp_dir, ard_parameters, subset, data_mount)
    153                                       border_noise=border_noise,
    154                                       subset=subset,
--> 155                                       polarisation=polarisation)
    156 
    157 

/opt/miniconda/envs/shared/lib/python3.7/site-packages/ost/s1/grd_to_ard.py in grd_to_ard(filelist, output_dir, file_id, temp_dir, resolution, product_type, ls_mask_create, speckle_filter, dem, to_db, border_noise, subset, polarisation)
    783 
    784             grd_import = opj(temp_dir, '{}_imported'.format(
--> 785                 os.path.basename(file)[:-5]))
    786             logfile = opj(output_dir, '{}.Import.errLog'.format(
    787                 os.path.basename(file)[:-5]))

/opt/miniconda/envs/shared/lib/python3.7/posixpath.py in basename(p)
    144 def basename(p):
    145     """Returns the final component of a pathname"""
--> 146     p = os.fspath(p)
    147     sep = _get_sep(p)
    148     i = p.rfind(sep) + 1

TypeError: expected str, bytes or os.PathLike object, not NoneType

note that I use parameter
OurProject.ard_parameters['polarisation'] = 'VV,VH'
but tried also to put:
OurProject.ard_parameters['polarisation'] = ['VV','VH']

no difference though

**Comment by BuddyVolly** [comment]
I see the bug, will adjust this in future release.
