### ISSUE TITLE
create_stack uses a wrong pattern

### ISSUE THREAD

**Issue by vincentvaroquaux** [ESA-PhiLab/OpenSarToolkit#40]
```
/ost/generic/common_wrappers.py
@@ -347,7 +347,7 @@ def create_stack(
         command = (
             f'{GPT_FILE} {graph} -x -q {2*cpus} '
             f'-Pfilelist={file_list} '
-            f'-PbandPattern=\'{pattern}.*\' '
+            f'-PbandPattern=\'.*{pattern}.*\' '
             f'-Poutput={out_stack}'
         )
 
```

**Comment by BuddyVolly** [comment]
ok, shouldn't do harm. But actually it looks for Alpha*, or Entropy*. so I do not see the need for using both. Did you have problems?

**Comment by vincentvaroquaux** [comment]
create_stack is also called with pol=VV, VH, HH and HV

```
def _create_timeseries(burst_gdf, config_file):
    # we need a
    dict_of_product_types = {'bs': 'Gamma0', 'coh': 'coh', 'pol': 'pol'}
    pols = ['VV', 'VH', 'HH', 'HV', 'Alpha', 'Entropy', 'Anisotropy']
[...]
        for pr, pol in itertools.product(dict_of_product_types.items(), pols):
[...]
    for task in executor.as_completed(
            func=ard_to_ts.gd_ard_to_ts,
```

```
def ard_to_ts(list_of_files, burst, product, pol, config_file):
[...]
        if pol in ['Alpha', 'Anisotropy', 'Entropy']:
[...]
        else:
[...]
                create_stack(
                    list_of_files, temp_stack, stack_log, config_dict,
                    polarisation=pol
                )
```

**Comment by BuddyVolly** [comment]
exactly, 

for Alpha, Entropy and Anisotropy it calls (not pattern keyword):

create_stack(
                    list_of_files, temp_stack, stack_log, config_dict,
                    pattern=pol
                )

and for the bs and coh bands it calls (see the polarsation keyword):

create_stack(
                    list_of_files, temp_stack, stack_log, config_dict,
                    polarisation=pol
                )

Dependent on the keyword used, it will use a different graph inside create_stack.

Yours is probably more elegant, and less code is needed, but it shouldn't be a problem, right? Or do you get errors?

thanks

**Comment by vincentvaroquaux** [comment]
You are right.
I did a fork where I changed the ard_to_ts function to always use the "pattern" parameter. That's why I had problems...
So there is no problem with your code and I apologize for that :)

**Comment by BuddyVolly** [comment]
No problem, I appreciate your help a lot! If you find further issues, please let me know.
Many thanks
