### ISSUE TITLE
GRD frame import exited with error -9

### ISSUE THREAD

**Issue by nicohrubec** [ESA-PhiLab/OpenSarToolkit#53]
Hello,

I am trying to preprocess Sentinel1 Data with this Toolkit. At first, the Docker build process did not work with the provided Dockerfile. A fixed it by doing:
1. Lbgfortran3 seems to be no longer available for Ubuntu 20, so I fixed it by using libgfortran5 instead.
2. I had to change the Orfeo Toolbox link to https://www.orfeo-toolbox.org/packages/archives/OTB/${OTB}
3. I deleted the installation of jupyterlab because this step failed because of nodejs version.

Is this fine so far or did I change anything that could break something? With these changes I could build and use the container. So now I am trying to preprocess the data like shown in the OST Tutorial Notebooks.

I set the parameters as:
`s1_grd.ard_parameters['single_ARD']['resolution'] = 50`
`s1_grd.ard_parameters['single_ARD']['remove_speckle'] = True`
`s1_grd.ard_parameters['single_ARD']['remove_mt_speckle'] = True`
`s1_grd.ard_parameters['mosaic']['cut_to_aoi'] = True`
`s1_grd.ard_parameters['single_ARD']['dem']['dem_name'] = 'SRTM 1Sec HGT'`

where s1_grd is an instance of Sentinel1Batch class. Then I call s1_grd.grds_to_ards with parameters: timeseries=True, timescan=False, mosaic=False, overwrite=False. 

This works fine for some files, but for other I always get the following error: GRD frame import exited with error -9
It also says that there is a Snap error log file available called 20180130_15.Import.errLog, but the only thing logged in the files is:
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.hsqldb.persist.Logger: dataFileCache open start

Now I have no idea how to proceed or where to look further. Do you have any idea what this error could mean or maybe how to solve it? Or do you have any pointers for where I could potentially find out more about this? I have tried to solve this issue for a while now and I am running out of ideas. Any help would be highly appreciated. If you need me to provide any more information please let me know.

Best wishes,
Nico

**Comment by KBodolai** [comment]
I just stumbled upon that same issue myself, running the [first notebook tutorial](https://github.com/ESA-PhiLab/OST_Notebooks/blob/master/1%20-%20The%20first%20S1%20scene.ipynb) after installing it on a fresh ubuntu 20.04 machine in AWS to check it worked fine. (so everything according to the [installation shell script](https://github.com/ESA-PhiLab/OST_Notebooks/blob/master/install_ost.sh) ). Same thing exactly worked yesterday con colab. I'll try with a new one to see if it persists, and will do some more digging.

**Comment by BuddyVolly** [comment]
I need to investigate that more in detail, but I am busy with other stuff right now. 
Please check the SNAP forum, if this issue has been reported already. It might only occur for certain SNAP versions?

**Comment by KBodolai** [comment]
This didn't happen to me again, which leads me to believe it was indeed something to do with SNAP version (I think it didn't update that time)

@nicohrubec , were you able to replicate it?
