### ISSUE TITLE
javaImport Error with custom GPT, only when copied to .ost/gpt

### ISSUE THREAD

**Issue by Scartography** [ESA-PhiLab/OpenSarToolkit#6]
It seems that executing gpt in some environments (here Ubuntu 18.04. and python venv 3.6) from the .ost/gpt folder won't recognize the java environment and fails at importing some core java libraries.

Basically commenting/deleting these lines solves the issue:
https://github.com/ESA-PhiLab/OpenSarToolkit/blob/2472258681d78fbc95f30dc3f676b9d8117c69f3/ost/helpers/helpers.py#L81-L82

Recommending using just the GPT installed via user. For isntance to get a GPT_Path from a specific env. variable like `os.getenv('gpt_path')`

Petr

**Comment by BuddyVolly** [comment]
yes, I just figured that. I think it is because gpt refers inside to relative paths, and not absolute ones. I replaced the copy command with a symbolic link. Not sure if that will work on windows, but it should solve it for Ubuntu.
