### ISSUE TITLE
use comitizen to bump versions 

### ISSUE THREAD

**Issue by 12rambau** [ESA-PhiLab/OpenSarToolkit#61]
Comitizen is a Python tool developed to make automatic publication easy and generate meaningful semVer number and automatic chagelog. 

That's piece of cake to implement and once it's their you'll never have to worry about numbers ;-)

https://commitizen-tools.github.io/commitizen/

**Comment by KBodolai** [comment]
We can probably close this issue, right, @12rambau ?
