### ISSUE TITLE
speckle filter deletes its own output 

### ISSUE THREAD

**Issue by Scartography** [ESA-PhiLab/OpenSarToolkit#7]
Here the `data_dir` discovers the output of the speckle filtering as well and deletes it:

https://github.com/ESA-PhiLab/OpenSarToolkit/blob/2472258681d78fbc95f30dc3f676b9d8117c69f3/ost/s1/grd_to_ard.py#L872-L874

* Specify what to delete, check naming conventions for temp files.

Petr

**Comment by BuddyVolly** [comment]
I solved it, and I am doing a couple of other things. Once you can see the issues closed here, a new version will be pushed with the changes applied. Should be latest end of next week.
