### ISSUE TITLE
iso3 country code not working

### ISSUE THREAD

**Issue by BuddyVolly** [ESA-PhiLab/OpenSarToolkit#75]

**Comment by KBodolai** [comment]
in which version is this? I just ran a colab notebook with 'AUT' and it seems to work fine

**Comment by 12rambau** [comment]
I never looked at how you implemented the countries in OST, but do you think it would make sense to integrate the GADM database (I could adapt what I'm doing in sepal_ui)

**Comment by BuddyVolly** [comment]
@KBodolai might be a geopandas/shapely versioning issue, as it states it doesn't recognize to_wkt() ? need to check wisely then 
@12rambau GADM would be nice, as at the moment it is using geopandas boundaries which are VERY rough. but GADM might have a license issue if I remember ?

**Comment by KBodolai** [comment]
I just checked the code, and it should definitely not be calling `to_wkt()`, it should be doing `.wkt`, which is the error I fixed in the past.

Maybe you have installed an older version of the lib?

**Comment by BuddyVolly** [comment]
I messed my local install and symbolic links, you are right as it is in the main branch like this

**Comment by 12rambau** [comment]
> @KBodolai might be a geopandas/shapely versioning issue, as it states it doesn't recognize to_wkt() ? need to check wisely then
> @12rambau GADM would be nice, as at the moment it is using geopandas boundaries which are VERY rough. but GADM might have a license issue if I remember ?

I'll check but if remember correctly not as long as OST remain open

**Comment by KBodolai** [comment]
Brief on their policy [here](https://gadm.org/data.html) and link to their license. 

Issue may be how this affects people using it for a commercial setting, does it transfer?

**Comment by 12rambau** [comment]
Ok I'm sending an email to them first (as I think my other lib is not fully respecting their License as well
