### ISSUE TITLE
Autodoc skipping first argument.

### ISSUE THREAD

**Issue by KBodolai** [ESA-PhiLab/OpenSarToolkit#77]
When autogenerating the API reference from the docstrings, autodoc is missing the first parameter (see image below), so `f(a,b,c)` shows like `f(b,c)`

<img src="https://user-images.githubusercontent.com/69843715/148185428-e135f391-4760-4a7f-9080-37d292f02617.png" width="300" height="300">

**To reproduce**
Build the docs with sphinx, and open any file of the API reference (example from ost.helpers.vector)

**Expected behavior**
All arguments showing.

**Additional context**
Also showing in our rtd documentation. Behaviour looks very much like you would expect in class methods, where it skips the `self` param.

**Comment by 12rambau** [comment]
got it. It is as simple as a directive name: 

`.. automethod::` is dedicated to object method so it by design skip the first (`self`) parameter unless the method is static. 
`.. autofunction::` is for module function and don't skip anything

I'll change everything in my branch
